name: Deploy

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run build
      - run: npm run deploy
        env:
          USE_SSH: true
          GH_PAGES_DEPLOY: github-actions[bot]@users.noreply.github.com
          GIT_USER: 'kafn1003'